# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
    - refs/pull/*
  paths:
    include:
    - worker/*
    - .azure-pipelines/worker-cicd.yaml
    - manifests/worker.yaml

resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: N-Usha/voting-app-ci-templates
    endpoint: github.com_N-Usha

variables:
#- group: VoterAppSecrets  

- name: dockerRegistryServiceConnection 
  value: '621a834f-49c3-4f4e-a151-fa59b0924954'
- name: imageRepository 
  value: 'gevergheworkerappkubernetes'
- name: containerRegistry 
  value: 'forresterdemo.azurecr.io'
- name: dockerfilePath 
  value: 'worker/Dockerfile'
- name: tag 
  value: '$(Build.BuildId)'
- name: imagePullSecret 
  value: 'forresterdemosecret'
- name: azure-storage-secret 
  value: 'azure-storage'
- name: azure-sql-secret 
  value: 'azure-sql'
- name: k8sNamespaceForPR 
  value: '$(system.pullRequest.sourceBranch)'

  # Agent VM image name
- name: vmImageName 
  value: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - template: buildJob.yml@templates
    parameters:
      name: 'worker'
      vmImageName: $(vmImageName)
      imageRepository: $(imageRepository)
      dockerfilePath: $(dockerfilePath)
      dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
      tag: $(tag)

- stage: IaC
  displayName: IaC
  dependsOn: Build
  jobs:    
  - job: createOrUpdateACR
    displayName: Create Or Update ACR - ForresterDemo     
    steps:    
    - task: AzureKeyVault@1
      displayName: Fetch Storage Secrets from Azure Key vault
      inputs:
        azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
        KeyVaultName: 'ForresterDemoKeyVault'
        SecretsFilter: '*'    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
        subscriptionId: 'afc11291-9826-46be-b852-70349146ddf8'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'ForresterDemo'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/arm-templates/acr.json'
        overrideParameters: -acrName "ForresterDemo" -acrSku "Premium"
        deploymentMode: 'Incremental'
    
- stage: ReviewApp
  displayName: Deploy Pull Request
  dependsOn: IaC
  jobs:
  - deployment: DeployPullRequest
    displayName: Deploy Pull request
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: $(vmImageName)      
    environment: 'Development.$(k8sNamespaceForPR)' 
    strategy:
      runOnce:
        deploy:
          steps:
          - reviewApp: contoso-dev-aks

          - task: Kubernetes@1
            displayName: 'Create a new namespace for the pull request'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              namespace: '$(k8sNamespaceForPR)'
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: AzureKeyVault@1
            displayName: Fetch Storage Secrets from Azure Key vault
            inputs:
              azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
              KeyVaultName: 'ForresterDemoKeyVault'
              SecretsFilter: '*'

          - task: KubernetesManifest@0
            displayName: Create storage secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-storage-secret)
              secretArguments: --from-literal=account-name=$(azure-storage-dev-username) --from-literal=access-key=$(azure-storage-dev-key)
              kubernetesServiceConnection: 'Development-contoso-dev-aks-1582199981119'
              namespace: '$(k8sNamespaceForPR)'

          - task: KubernetesManifest@0
            displayName: Create SQL secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-sql-secret)
              secretArguments: --from-literal=sql-hostname=$(azure-sql-hostname-dev) --from-literal=sql-username=$(azure-sql-rw-username) --from-literal=sql-password=$(azure-sql-rw-password)
              kubernetesServiceConnection: 'Development-contoso-dev-aks-1582199981119'
              namespace: '$(k8sNamespaceForPR)'

          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: bake
              renderType: helm2
              helmChart: $(Pipeline.Workspace)/worker/helm
          
          - task: KubernetesManifest@0
            displayName: Deploy to the new namespace in the Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespaceForPR)
              manifests: $(bake.manifestsBundle)
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

- stage: DeployToDev
  displayName: Deploy to Development
  dependsOn: IaC
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'Development.contoso-dev-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
          #     scriptType: 'bash'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: 'az devops project list'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              namespace: "contoso-dev-aks"
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: AzureKeyVault@1
            displayName: Fetch Storage Secrets from Azure Key vault
            inputs:
              azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
              KeyVaultName: 'ForresterDemoKeyVault'
              SecretsFilter: '*'

          - task: KubernetesManifest@0
            displayName: Create storage secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-storage-secret)
              secretArguments: --from-literal=account-name=$(azure-storage-dev-username) --from-literal=access-key=$(azure-storage-dev-key)
              kubernetesServiceConnection: 'Development-contoso-dev-aks-1582199981119'
              namespace: "contoso-dev-aks"

          - task: KubernetesManifest@0
            displayName: Create SQL secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-sql-secret)
              secretArguments: --from-literal=sql-hostname=$(azure-sql-hostname-dev) --from-literal=sql-username=$(azure-sql-rw-username) --from-literal=sql-password=$(azure-sql-rw-password)
              kubernetesServiceConnection: 'Development-contoso-dev-aks-1582199981119'
              namespace: 'contoso-dev-aks'

          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: bake
              renderType: helm2
              helmChart: $(Pipeline.Workspace)/worker/helm

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: "contoso-dev-aks"
              manifests: $(bake.manifestsBundle)
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

- stage: DeployToQA
  displayName: Deploy to QA
  dependsOn: DeployToDev
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'QA.contoso-qa-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              namespace: "contoso-qa-aks"
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: AzureKeyVault@1
            displayName: Fetch Storage Secrets from Azure Key vault
            inputs:
              azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
              KeyVaultName: 'ForresterDemoKeyVault'
              SecretsFilter: '*'

          - task: KubernetesManifest@0
            displayName: Create storage secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-storage-secret)
              secretArguments: --from-literal=account-name=$(azure-storage-qa-username) --from-literal=access-key=$(azure-storage-qa-key)
              kubernetesServiceConnection: 'QA-contoso-qa-aks-1582637596513'
              namespace: "contoso-qa-aks"

          - task: KubernetesManifest@0
            displayName: Create SQL secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-sql-secret)
              secretArguments: --from-literal=sql-hostname=$(azure-sql-hostname-qa) --from-literal=sql-username=$(azure-sql-rw-username) --from-literal=sql-password=$(azure-sql-rw-password)
              kubernetesServiceConnection: 'QA-contoso-qa-aks-1582637596513'
              namespace: 'contoso-qa-aks'

          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: bake
              renderType: helm2
              helmChart: $(Pipeline.Workspace)/worker/helm

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: "contoso-qa-aks"
              manifests: $(bake.manifestsBundle)
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

- stage: DeployProdAKS
  displayName: Deploy to Production AKS
  dependsOn: DeployToQA

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'Production.contoso-prod-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: 'contoso-prod-aks'
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: AzureKeyVault@1
            displayName: Fetch Storage Secrets from Azure Key vault
            inputs:
              azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
              KeyVaultName: 'ForresterDemoKeyVault'
              SecretsFilter: '*'
          
          - task: KubernetesManifest@0
            displayName: Create storage secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-storage-secret)
              secretArguments: --from-literal=account-name=$(azure-storage-username) --from-literal=access-key=$(azure-storage-key)
              kubernetesServiceConnection: 'Production-contoso-prod-aks-1582200387426'
              namespace: 'contoso-prod-aks'

          - task: KubernetesManifest@0
            displayName: Create SQL secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-sql-secret)
              secretArguments: --from-literal=sql-hostname=$(azure-sql-hostname) --from-literal=sql-username=$(azure-sql-rw-username) --from-literal=sql-password=$(azure-sql-rw-password)
              kubernetesServiceConnection: 'Production-contoso-prod-aks-1582200387426'
              namespace: 'contoso-prod-aks'

          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: bake
              renderType: helm2
              helmChart: $(Pipeline.Workspace)/worker/helm
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: $(bake.manifestsBundle)
              namespace: 'contoso-prod-aks'           
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
                
- stage: DeployProdGKE
  displayName: Deploy to Production GKE 
  dependsOn: DeployToQA  

  jobs:
  - deployment: Deploy
    displayName: Deploy    
    pool:
      vmImage: $(vmImageName)
    environment: 'Production.contoso-prod-gke'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: 'contoso-prod-gke'
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: AzureKeyVault@1
            displayName: Fetch Storage Secrets from Azure Key vault
            inputs:
              azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
              KeyVaultName: 'ForresterDemoKeyVault'
              SecretsFilter: '*'
          
          - task: KubernetesManifest@0
            displayName: Create storage secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-storage-secret)
              secretArguments: --from-literal=account-name=$(azure-storage-username) --from-literal=access-key=$(azure-storage-key)
              kubernetesServiceConnection: 'Production-contoso-prod-gke-1582202369145'
              namespace: 'contoso-prod-gke'

          - task: KubernetesManifest@0
            displayName: Create SQL secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-sql-secret)
              secretArguments: --from-literal=sql-hostname=$(azure-sql-hostname) --from-literal=sql-username=$(azure-sql-rw-username) --from-literal=sql-password=$(azure-sql-rw-password)
              kubernetesServiceConnection: 'Production-contoso-prod-gke-1582202369145'
              namespace: 'contoso-prod-gke'

          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: bake
              renderType: helm2
              helmChart: $(Pipeline.Workspace)/worker/helm
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: $(bake.manifestsBundle)
              namespace: 'contoso-prod-gke'           
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
                
